version: '3.4'

services:
  db:
    image: ontopicvkg/odh-tourism-db:1.0
    restart: unless-stopped
    ports:
      - "${PG_DOCKER_PORT}:5432"
    environment:
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
  app:
    image: ontop/ontop-endpoint:4.0-snapshot
    restart: unless-stopped
    environment:
      - ONTOP_ONTOLOGY_FILE=/opt/ontop/input/odh.ttl
      - ONTOP_MAPPING_FILE=/opt/ontop/input/odh.obda
      - ONTOP_PROPERTIES_FILE=/opt/ontop/input/odh.docker.properties
      - ONTOP_CORS_ALLOWED_ORIGINS=*
      - ONTOP_LAZY_INIT=true
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    ports:
      - "${DOCKER_SERVER_PORT}:8080"
